[package]
name = "encore"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.2.1"
compiler_builtins = "0.1.39"
displaydoc = { version = "0.1.7", default-features = false }
linked_list_allocator = "0.9.*"
rlibc = "1.0.0"
